insert into categorie_ingredient (id, nom_categorie) values (1, 'bases');
insert into categorie_ingredient (id, nom_categorie) values (2, 'pates');
insert into categorie_ingredient (id, nom_categorie) values (3, 'ingredients pates pizza');
insert into categorie_ingredient (id, nom_categorie) values (4, 'viandes & poissons');
insert into categorie_ingredient (id, nom_categorie) values (5, 'fromages');
insert into categorie_ingredient (id, nom_categorie) values (6, 'condiments');
insert into categorie_ingredient (id, nom_categorie) values (7, 'legumes');
insert into categorie_ingredient (id, nom_categorie) values (8, 'boissons');
insert into categorie_ingredient (id, nom_categorie) values (9, 'snacks');
insert into categorie_ingredient (id, nom_categorie) values (10, 'desserts');
