DELETE FROM ingredient;

insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (1, 'Tomates', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (2, 'creme fraiche', 'g', 1);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (3, 'sauce tomate', 'g', 1);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (4, 'salade', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (5, 'champignon', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (6, 'coca', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (7, 'fanta', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (8, 'creme brulees', 'u', 10);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (9, 'mousse chocolat', 'u', 10);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (10, 'chicken wings', 'u', 9);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (11, 'roti', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (12, 'pennes', 'g', 2);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (13, 'lasagnes', 'g', 2);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (14, 'sauce boloniaise', 'g', 1);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (15, 'beurre', 'g', 3);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (16, 'camembert', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (17, 'fromage à fondue', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (18, 'sel', 'g', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (19, 'anchois', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (20, 'origan', 'g', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (21, 'olives', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (22, 'Poivrons ', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (23, 'Artichauts', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (24, 'Aubergine', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (25, 'Mozzarella', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (26, 'Basilic', 'g', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (27, 'Jambon', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (28, 'Thon', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (29, 'Chorizo', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (30, 'Cantal', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (31, 'EAU MINÉRALE', 'u', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (32, 'COCA 33CL', 'u', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (33, 'FANTA 33CL', 'u', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (34, 'NESTEA PECHE 33CL', 'u', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (35, 'FONDANT AU CHOCOLAT', 'u', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (36, 'fromage', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (37, 'câpres', 'g', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (38, 'persillade', 'g', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (39, 'maïs', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (40, 'gruyère', 'g', 5);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (41, 'coeur de palmier', 'g', 7);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (42, 'lardons', 'g', 4);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (43, 'EAU MINÉRALE', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (44, 'COCA 33CL', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (45, 'FANTA 33CL', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (46, 'NESTEA PECHE 33CL', 'u', 8);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (47, 'FONDANT AU CHOCOLAT', 'u', 10);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (48, 'GLACE  CHOCOLAT 100ML', 'u', 10);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (49, 'vinaigrette', 'ml', 6);
insert into ingredient (id, nom, unite_de_mesure, categorie_id) values (50, 'oeuf', 'u', 4);
