DELETE FROM produit;

insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (1, 8.057, 5.5, 'MARGUERITE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (2, 8.246, 5.5, 'NAPOLITAINE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (3, 8.530, 5.5, 'SICILIENNE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (4, 9.005, 5.5, '4 SAISONS', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (5, 9.005, 5.5, 'PAYSANNE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (6, 9.194, 5.5, 'ITALIENNE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (7, 9.194, 5.5, 'MARGUERITE EPAULE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (8, 10.137, 5.5, 'NEPTUNE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (9, 10.289, 5.5, 'ESPAGNOLE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (10, 9.573, 5.5, 'CANTAL', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (11, 9.763, 5.5, 'REINE', 'Transformé', 1);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (12, 6.825, 5.5, 'SALADE MOZZARELLA', 'Transformé', 4);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (13, 6.825, 5.5, 'SALADE CHEF', 'Transformé', 4);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (14, 6.825, 5.5, 'SALADE PASTA', 'Transformé', 4);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (15, 2.180, 5.5, 'SALADE VERTE', 'Transformé', 4);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (16, 6.825, 5.5, 'LASAGNE', 'Transformé', 2);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (17, 6.825, 5.5, 'PENNE CARBONARA', 'Transformé', 2);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (18, 1.137, 5.5, 'EAU MINÉRALE', 'Revente', 5);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (19, 1.706, 5.5, 'COCA 33CL', 'Revente', 5);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (20, 1.706, 5.5, 'FANTA 33CL', 'Revente', 5);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (21, 1.706, 5.5, 'NESTEA PECHE 33CL', 'Revente', 5);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (22, 2.280, 5.5, 'FONDANT AU CHOCOLAT', 'Revente', 6);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (23, 2.843, 5.5, 'GLACE  CHOCOLAT 100ML', 'Revente', 6);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (24, 1.137, 5.5, 'supplément cantal', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (25, 1.137, 5.5, 'supplément chorizo', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (26, 1.137, 5.5, 'supplément anchois', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (27, 1.137, 5.5, 'supplément Artichauts', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (28, 1.137, 5.5, 'supplément Mozzarella', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (29, 1.896, 5.5, 'supplément jambon', 'Suppléments', 7);
insert into produit (id, prix_unitaire_HT, taux_TVA_100, nom, type_produit, categorie_id) values (30, 1.137, 5.5, 'supplément oeuf', 'Suppléments', 7);
