DELETE FROM mb_staff;

insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (1, 'Kinglake', 'Marie-noël', 'serveur', 'bkinglake0@nymag.com', 'ZP2DZs5Dyyp', '5416863045');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (2, 'Killiner', 'Anaëlle', 'serveur','gkilliner1@photobucket.com', 'xzG6dlIP', '5842923458');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (3, 'Featherby', 'Yénora', 'serveur', 'ffeatherby2@mozilla.com', '9ehd2I4', '3046262888');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (4, 'Partridge', 'Léone', 'serveur','lpartridge3@usa.gov', 'qUwIGjZO', '2254297068');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (5, 'Merrall', 'Almérinda', 'serveur', 'amerrall4@oracle.com', 'Bfbjkj8j', '8752744571');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (6, 'Ollander', 'Bécassine', 'serveur', 'nollander5@admin.ch', '2GfMr0LMc8', '6513659332');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (7, 'Itzkovsky', 'Tán', 'serveur', 'sitzkovsky6@amazon.co.uk', 'FdgeCTkgp', '6546808504');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (8, 'Nevill', 'Vénus', 'serveur', 'knevill7@sciencedirect.com', 'vHVKFt3ph', '2274571323');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (9, 'Olive', 'Rachèle', 'serveur', 'colive8@statcounter.com', 'iXcHwcnkv', '4321133010');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (10, 'Axelbee', 'Simplifiés', 'pizzaiolo', 'kaxelbee9@cbsnews.com', '1yqzF6q1ZmuO', '3427691594');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (11, 'Dreye', 'Marie-josée', 'pizzaiolo', 'fdreyea@fc2.com', 'p11jSW6e', '3636487821');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (12, 'Calver', 'Laïla', 'pizzaiolo', 'ncalverb@berkeley.edu', 'LmRXSCH2N0', '5118535146');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (13, 'Dundon', 'Magdalène', 'pizzaiolo', 'ddundonc@cloudflare.com', 'BIGlaT5', '1174106835');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (14, 'Grayer', 'Athéna', 'pizzaiolo', 'egrayerd@cloudflare.com', 'gWfvdtG7o', '3469672336');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (15, 'Tampen', 'Gaïa', 'pizzaiolo', 'mtampene@rambler.ru', '8BhBduQ', '5837884768');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (16, 'Poyner', 'Kallisté', 'pizzaiolo', 'rpoynerf@mozilla.org', 'NtzOYQ5tJu', '8162906243');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (17, 'McGraith', 'Maëline', 'pizzaiolo', 'mmcgraithg@theatlantic.com', 'rYj6ZuXi5', '9732953596');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (18, 'Greenman', 'Méthode', 'pizzaiolo', 'fgreenmanh@soup.io', 'yOPJlkpu', '9817756409');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (19, 'Beedham', 'Anaé', 'pizzaiolo', 'bbeedhami@slate.com', '0OIxY5w', '3327889272');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (20, 'Zorzin', 'Aimée', 'livreur', 'pzorzinj@domainmarket.com', 'VjHIZcRFTF7s', '2052921814');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (21, 'Rubert', 'Célestine', 'livreur', 'grubertk@gizmodo.com', 'PjESG5', '6499607611');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (22, 'Kupke', 'Léone', 'livreur', 'nkupkel@cdbaby.com', 'xj9pwWb', '1592705162');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (23, 'Gillet', 'Danièle', 'livreur', 'rgilletm@yahoo.com', 'qDH2n6UUOq', '8915344891');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (24, 'Seager', 'Björn', 'livreur', 'lseagern@networksolutions.com', 'Gkmi16U22bL', '9473585787');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (25, 'Ellery', 'Mélissandre', 'livreur', 'eelleryo@smugmug.com', 'gGKw73vv', '4341819206');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (26, 'Izzett', 'Céline', 'livreur', 'mizzettp@yandex.ru', '3OnF6Dk', '8249075960');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (27, 'Upham', 'Mahélie', 'livreur', 'muphamq@princeton.edu', 'rYffyUQfYicr', '6415962015');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (28, 'Pleavin', 'Jú', 'livreur', 'gpleavinr@ftc.gov', '06RR6AekQ9M', '1519505517');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (29, 'Cady', 'Åsa', 'livreur', 'vcadys@goo.ne.jp', 'p0Nbvf', '6401542551');
insert into mb_staff (identifiant, nom, prenom, poste_principal, mail, password, tel) values (30, 'Alexandersson', 'livreur', 'pizzaiolo', 'ealexanderssont@xinhuanet.com', 'K6TXRp', '1627686214');
